name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and PUSH Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: prashantflick/dummy-bank:latest
      
    - name: Verify Pushed Image
      run: docker pull prashantflick/dummy-bank:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_KEY}}
        script: |
          sudo docker pull prashantflick/dummy-bank:latest
          sudo docker stop dummy-bank || true
          sudo docker rm dummy-bank || true
          sudo docker run --name dummy-bank -d -p 3004:3004 prashantflick/dummy-bank:latest

